create database if not exists dc_storage;
use dc_storage;
drop table if exists click;
CREATE EXTERNAL TABLE click
(`platform` string,`dt` string,`message_id` string,`project_id` string,`app_id` string,`app_version` string,`tenant_id` string,`upload_time` string,`apex_id` string,`session_id` string,`app_package_id` string,`carrier` string,`mini_program_scene` string,`market_name` string,`sdk_version` string,`sdk_type` string,`device_id` string,`device_model` string,`device_brand` string,`device_type` string,`device_uuid` string,`android_id` string,`imei` string,`mac` string,`user_agent` string,`idfa` string,`idfv` string,`oaid` string,`screen_height` string,`screen_width` string,`os_system` string,`os_version` string,`browser_type` string,`browser_version` string,`wechat_open_id` string,`wechat_union_id` string,`referrer_url` string,`referrer_host` string,`utm_matching_type` string,`utm_source` string,`utm_medium` string,`utm_term` string,`utm_content` string,`utm_campaign` string,`event_code` string,`event_name` string,`event_type` string,`send_type` string,`page_type` string,`ts` timestamp,`network_type` string,`time_since_last_operation` string,`event_code_md5` string,`page_X` string,`page_Y` string,`client_X` string,`client_Y` string,`element_id` string,`element_name` string,`element_target_url` string,`element_type` string,`element_content` string,`element_selector` string,`element_position` string,`element_index` string,`element_tag_name` string,`element_class` string,`element_path` string,`user_id` string,`extensions` string,`ip` string,`latitude` string,`longitude` string,`province` string,`city` string,`country` string,`province_id` string,`city_id` string,`county` string,`current_page_id` string,`current_page_name` string,`current_page_url` string,`current_page_host` string,`current_page_query` string,`current_page_path` string,`source_page_id` string,`source_page_name` string,`source_page_url` string,`source_page_host` string,`source_page_query` string,`source_page_path` string,`visible_window_width` string,`visible_window_height` string,`page_height` string,`page_width` string)
PARTITIONED BY (`ds` string)
 stored as orc
 LOCATION '/user/hive/warehouse/dcp/dc-storage/click/';

drop table if exists view_page;
CREATE EXTERNAL TABLE view_page
(`platform` string,`dt` string,`message_id` string,`project_id` string,`app_id` string,`app_version` string,`tenant_id` string,`upload_time` string,`apex_id` string,`session_id` string,`app_package_id` string,`carrier` string,`mini_program_scene` string,`market_name` string,`sdk_version` string,`sdk_type` string,`device_id` string,`device_model` string,`device_brand` string,`device_type` string,`device_uuid` string,`android_id` string,`imei` string,`mac` string,`user_agent` string,`idfa` string,`idfv` string,`oaid` string,`screen_height` string,`screen_width` string,`os_system` string,`os_version` string,`browser_type` string,`browser_version` string,`wechat_open_id` string,`wechat_union_id` string,`referrer_url` string,`referrer_host` string,`utm_matching_type` string,`utm_source` string,`utm_medium` string,`utm_term` string,`utm_content` string,`utm_campaign` string,`event_code` string,`event_name` string,`event_type` string,`send_type` string,`page_type` string,`ts` timestamp,`network_type` string,`time_since_last_operation` string,`event_code_md5` string,`browse_time` string,`user_id` string,`extensions` string,`ip` string,`latitude` string,`longitude` string,`province` string,`city` string,`country` string,`province_id` string,`city_id` string,`county` string,`current_page_id` string,`current_page_name` string,`current_page_url` string,`current_page_host` string,`current_page_query` string,`current_page_path` string,`source_page_id` string,`source_page_name` string,`source_page_url` string,`source_page_host` string,`source_page_query` string,`source_page_path` string,`visible_window_width` string,`visible_window_height` string,`page_height` string,`page_width` string)
PARTITIONED BY (`ds` string)
 stored as orc
 LOCATION '/user/hive/warehouse/dcp/dc-storage/view_page/';

drop table if exists custom;
CREATE EXTERNAL TABLE custom
(`platform` string,`dt` string,`message_id` string,`project_id` string,`app_id` string,`app_version` string,`tenant_id` string,`upload_time` string,`apex_id` string,`session_id` string,`app_package_id` string,`carrier` string,`mini_program_scene` string,`market_name` string,`sdk_version` string,`sdk_type` string,`device_id` string,`device_model` string,`device_brand` string,`device_type` string,`device_uuid` string,`android_id` string,`imei` string,`mac` string,`user_agent` string,`idfa` string,`idfv` string,`oaid` string,`screen_height` string,`screen_width` string,`os_system` string,`os_version` string,`browser_type` string,`browser_version` string,`wechat_open_id` string,`wechat_union_id` string,`referrer_url` string,`referrer_host` string,`utm_matching_type` string,`utm_source` string,`utm_medium` string,`utm_term` string,`utm_content` string,`utm_campaign` string,`event_code` string,`event_name` string,`event_type` string,`send_type` string,`page_type` string,`ts` timestamp,`network_type` string,`time_since_last_operation` string,`user_id` string,`extensions` string,`ip` string,`latitude` string,`longitude` string,`province` string,`city` string,`country` string,`province_id` string,`city_id` string,`county` string,`current_page_id` string,`current_page_name` string,`current_page_url` string,`current_page_host` string,`current_page_query` string,`current_page_path` string,`source_page_id` string,`source_page_name` string,`source_page_url` string,`source_page_host` string,`source_page_query` string,`source_page_path` string,`visible_window_width` string,`visible_window_height` string,`page_height` string,`page_width` string)
PARTITIONED BY (`ds` string)
 stored as orc
 LOCATION '/user/hive/warehouse/dcp/dc-storage/custom/';

drop table if exists cold_start;
CREATE EXTERNAL TABLE cold_start
(`platform` string,`dt` string,`message_id` string,`project_id` string,`app_id` string,`app_version` string,`tenant_id` string,`upload_time` string,`apex_id` string,`session_id` string,`app_package_id` string,`carrier` string,`mini_program_scene` string,`market_name` string,`sdk_version` string,`sdk_type` string,`device_id` string,`device_model` string,`device_brand` string,`device_type` string,`device_uuid` string,`android_id` string,`imei` string,`mac` string,`user_agent` string,`idfa` string,`idfv` string,`oaid` string,`screen_height` string,`screen_width` string,`os_system` string,`os_version` string,`browser_type` string,`browser_version` string,`wechat_open_id` string,`wechat_union_id` string,`referrer_url` string,`referrer_host` string,`utm_matching_type` string,`utm_source` string,`utm_medium` string,`utm_term` string,`utm_content` string,`utm_campaign` string,`event_code` string,`event_name` string,`event_type` string,`send_type` string,`page_type` string,`ts` timestamp,`network_type` string,`time_since_last_operation` string,`user_id` string,`extensions` string,`ip` string,`latitude` string,`longitude` string,`province` string,`city` string,`country` string,`province_id` string,`city_id` string,`county` string)
PARTITIONED BY (`ds` string)
 stored as orc
 LOCATION '/user/hive/warehouse/dcp/dc-storage/cold_start/';

drop table if exists hot_start;
CREATE EXTERNAL TABLE hot_start
(`platform` string,`dt` string,`message_id` string,`project_id` string,`app_id` string,`app_version` string,`tenant_id` string,`upload_time` string,`apex_id` string,`session_id` string,`app_package_id` string,`carrier` string,`mini_program_scene` string,`market_name` string,`sdk_version` string,`sdk_type` string,`device_id` string,`device_model` string,`device_brand` string,`device_type` string,`device_uuid` string,`android_id` string,`imei` string,`mac` string,`user_agent` string,`idfa` string,`idfv` string,`oaid` string,`screen_height` string,`screen_width` string,`os_system` string,`os_version` string,`browser_type` string,`browser_version` string,`wechat_open_id` string,`wechat_union_id` string,`referrer_url` string,`referrer_host` string,`utm_matching_type` string,`utm_source` string,`utm_medium` string,`utm_term` string,`utm_content` string,`utm_campaign` string,`event_code` string,`event_name` string,`event_type` string,`send_type` string,`page_type` string,`ts` timestamp,`network_type` string,`time_since_last_operation` string,`user_id` string,`extensions` string,`ip` string,`latitude` string,`longitude` string,`province` string,`city` string,`country` string,`province_id` string,`city_id` string,`county` string)
PARTITIONED BY (`ds` string)
 stored as orc
 LOCATION '/user/hive/warehouse/dcp/dc-storage/hot_start/';

drop table if exists use_end;
CREATE EXTERNAL TABLE use_end
(`platform` string,`dt` string,`message_id` string,`project_id` string,`app_id` string,`event_duration` string,`app_version` string,`tenant_id` string,`upload_time` string,`apex_id` string,`session_id` string,`app_package_id` string,`carrier` string,`mini_program_scene` string,`market_name` string,`sdk_version` string,`sdk_type` string,`device_id` string,`device_model` string,`device_brand` string,`device_type` string,`device_uuid` string,`android_id` string,`imei` string,`mac` string,`user_agent` string,`idfa` string,`idfv` string,`oaid` string,`screen_height` string,`screen_width` string,`os_system` string,`os_version` string,`browser_type` string,`browser_version` string,`wechat_open_id` string,`wechat_union_id` string,`referrer_url` string,`referrer_host` string,`utm_matching_type` string,`utm_source` string,`utm_medium` string,`utm_term` string,`utm_content` string,`utm_campaign` string,`event_code` string,`event_name` string,`event_type` string,`send_type` string,`page_type` string,`ts` timestamp,`network_type` string,`time_since_last_operation` string,`user_id` string,`extensions` string,`ip` string,`latitude` string,`longitude` string,`province` string,`city` string,`country` string,`province_id` string,`city_id` string,`county` string)
PARTITIONED BY (`ds` string)
 stored as orc
 LOCATION '/user/hive/warehouse/dcp/dc-storage/use_end/';